### ISSUE TITLE
Cria CRUD de Logs: Criar Entity, Service, Controller, Repository

### ISSUE THREAD

**Issue by RobertoRosa7** [Epic-Pixel-devs/ha-ms-service-base#2]

**Comment by MARCIAHELENALIMA** [comment]
Esta tarefa envolve a criação de um CRUD completo para o registro de logs. As responsabilidades incluem:

1. **Criar a Entity**: Definir a estrutura de dados do log, incluindo todos os campos necessários.
2. **Criar o Service**: Implementar a lógica de negócios para operações CRUD no log.
3. **Criar o Controller**: Gerenciar as solicitações e respostas HTTP, fazendo a ligação entre o Service e o cliente.
4. **Criar o Repository**: Configurar a interface para o banco de dados, permitindo operações CRUD no log.

Por favor, coordenem entre si para dividir o trabalho de maneira eficaz.
